version: "3"
services:

  pub-sub-manager:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  pub-sub:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: master
      POSTGRES_DB: delivery
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  cache:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
			- /data:/data
			
  ingress-controller: 
		image: nginx:latest
		ports:
			- 80:80
			- 443:443
    volumes:
			- ./data/nginx:/etc/nginx/conf.d
			- ./data/certbot/conf:/etc/letsencrypt
			- ./data/certbot/www:/var/www/certbot
	
	ingress-certificate:
		image: certbot/certbot
		volumes:
		  -	./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot