apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: localhost
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_CREATE_TOPICS
            value: "a516817-kentekens:1:1,customer-selection-consolidation:1:1"
        volumeMounts:
          - name: kafka-persistent-storage
            mountPath: /data
      volumes:
        - name: kafka-persistent-storage
          persistentVolumeClaim:
            claimName: kafka-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: http
      port: 9092
      nodePort: 30090
  type: NodePort